---
name: CI/CD Python

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      # [Étapes existantes de test...]
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # ... autres étapes de test

  deploy:
    needs: test  # Attend que les tests passent
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Ne déploie que sur la branche main
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Déployer sur Render
        uses: render-actions/deploy@v1
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          # Options supplémentaires:
          # auto-deploy: true  # Déploie automatiquement
          # wait: true        # Attend la fin du déploiement